# Generated by Django 5.2.7 on 2025-10-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=50, verbose_name='Tittle')),
                ('anons', models.CharField(max_length=250, verbose_name='Anons')),
                ('content', models.TextField(verbose_name='Content')),
                ('pub_date', models.DateTimeField(verbose_name='Pub_date')),
            ],
        ),
    ]
